import Head from "next/head";
import Component_1 from "@/components/Component_1";

export default function Home() {
  return (
    <>
      <Head>
        <title>myContext</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component_1 />
    </>
  );
}
